# Generated by Django 2.2.3 on 2019-07-12 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_auto_20190712_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
