# Generated by Django 2.2.3 on 2019-07-12 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_auto_20190712_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
